# Generated by Django 2.2 on 2020-01-31 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('price', models.IntegerField(default=1000, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('slots', models.IntegerField(default=2, verbose_name=django.core.validators.MaxValueValidator(10))),
                ('hp_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('atk_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('def_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('int_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('spd_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorDface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=100, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('roll_value', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('critical', models.CharField(default='False', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('gold', models.IntegerField(default=500, verbose_name=django.core.validators.MaxValueValidator(9999999))),
                ('gems', models.IntegerField(default=60, verbose_name=django.core.validators.MaxValueValidator(999999))),
                ('hp_base', models.IntegerField(default=100, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('atk_base', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('def_base', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('int_base', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('spd_base', models.IntegerField(default=5, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('price', models.IntegerField(default=500, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('slots', models.IntegerField(default=2, verbose_name=django.core.validators.MaxValueValidator(10))),
                ('hp_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('atk_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('def_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('int_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('spd_boost', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='dice_hero_app.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='WpnDice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('price', models.IntegerField(default=1000, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wpn_dice', to='dice_hero_app.Hero')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wpn_dice', to='dice_hero_app.Weapon')),
            ],
        ),
        migrations.CreateModel(
            name='WpnDface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('price', models.IntegerField(default=50, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('roll_value', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(10))),
                ('critical', models.CharField(default='False', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wpn_dfaces', to='dice_hero_app.Hero')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wpn_dfaces', to='dice_hero_app.WpnDice')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=100, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('effect', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=100, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dice_hero_app.Hero')),
            ],
        ),
        migrations.AddField(
            model_name='hero',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', related_name='heroes', to='dice_hero_app.User'),
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('level', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('element', models.CharField(blank=None, max_length=15, null=None)),
                ('rolls', models.IntegerField(default=2, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('s1', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('s2', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('s3', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('s4', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('s5', models.IntegerField(default=2, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('s6', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(99))),
                ('gold', models.IntegerField(default=10, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('gems', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('hp_base', models.IntegerField(default=100, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('atk_base', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('def_base', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('int_base', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('spd_base', models.IntegerField(default=5, verbose_name=django.core.validators.MaxValueValidator(999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='enemy_drop', to='dice_hero_app.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armor_dfaces', models.ManyToManyField(blank=True, related_name='elements', to='dice_hero_app.ArmorDface')),
                ('armors', models.ManyToManyField(blank=True, related_name='elements', to='dice_hero_app.Armor')),
                ('enemies', models.ManyToManyField(blank=True, related_name='elements', to='dice_hero_app.Enemy')),
                ('heroes', models.ManyToManyField(blank=True, related_name='elements', to='dice_hero_app.Hero')),
                ('weapons', models.ManyToManyField(blank=True, related_name='elements', to='dice_hero_app.Weapon')),
                ('wpn_dfaces', models.ManyToManyField(blank=True, related_name='elements', to='dice_hero_app.WpnDface')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorDice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=2000, verbose_name=django.core.validators.MaxValueValidator(99999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor_dice', to='dice_hero_app.Hero')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor_dice', to='dice_hero_app.Armor')),
            ],
        ),
        migrations.AddField(
            model_name='armordface',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor_dfaces', to='dice_hero_app.Hero'),
        ),
        migrations.AddField(
            model_name='armordface',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor_dfaces', to='dice_hero_app.ArmorDice'),
        ),
        migrations.AddField(
            model_name='armor',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armors', to='dice_hero_app.Hero'),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=10, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('element', models.CharField(blank=True, default='None', max_length=15, null=True)),
                ('value', models.IntegerField(default=1, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('armordice', models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.ArmorDice')),
                ('armors', models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.Armor')),
                ('heroes', models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.Hero')),
                ('weapons', models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.Weapon')),
                ('wpndice', models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.WpnDice')),
            ],
        ),
    ]
