# Generated by Django 2.2 on 2020-01-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
