# Generated by Django 2.2 on 2020-01-26 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0002_auto_20200126_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(default=10, verbose_name=django.core.validators.MaxValueValidator(9999))),
                ('roll_value', models.IntegerField(default=0, verbose_name=django.core.validators.MaxValueValidator(10))),
                ('critical', models.CharField(default='False', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='basic_dfaces', to='dice_hero_app.ArmorDice')),
            ],
        ),
    ]
