# Generated by Django 2.2 on 2020-01-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0003_basicdface'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdface',
            old_name='parent',
            new_name='wpn_parent',
        ),
        migrations.AddField(
            model_name='basicdface',
            name='arm_parent',
            field=models.ManyToManyField(blank=True, related_name='basic_dfaces', to='dice_hero_app.WpnDice'),
        ),
    ]
