# Generated by Django 2.2 on 2020-01-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0004_auto_20200126_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdface',
            name='arm_parent',
            field=models.ManyToManyField(blank=True, related_name='basic_dfaces', to='dice_hero_app.ArmorDice'),
        ),
        migrations.AlterField(
            model_name='basicdface',
            name='wpn_parent',
            field=models.ManyToManyField(blank=True, related_name='basic_dfaces', to='dice_hero_app.WpnDice'),
        ),
    ]
