# Generated by Django 2.2 on 2020-01-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0005_auto_20200126_1547'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicDface',
        ),
    ]
