# Generated by Django 2.2 on 2020-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0006_delete_basicdface'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='armordice',
            field=models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.ArmorDice'),
        ),
        migrations.AddField(
            model_name='ability',
            name='wpndice',
            field=models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.WpnDice'),
        ),
    ]
