# Generated by Django 2.2 on 2020-01-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_hero_app', '0007_auto_20200126_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='armors',
            field=models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.Armor'),
        ),
        migrations.AddField(
            model_name='ability',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='abilities', to='dice_hero_app.Weapon'),
        ),
    ]
